### ISSUE TITLE
Include Category to PostCode Filter

### ISSUE THREAD

**Issue by price2b** [Vinai/VinaiKopp_PostCodeFilter#1]
thank you so much for your shared work. I read the specification and it would be great to mix postcode with categories. as an example, in crossborder ecommerce the most important thing is to know if the product will be release in a foreign customs and to avoid placing an order if that customer is from that country with customs limitations (eg: wines, food, health products).

mixing categories + postal codes in countries could provide merchants a greater control over customer experiences, avoiding packages returns, packages not released.

hope it could be easy to do. once again thank you. brgds!

**Comment by Vinai** [comment]
Thank you for your suggestion, but the purpose of this module is not to support cross border trade.

**Comment by price2b** [comment]
thank you for your reply!.
